info:
  contact: {}
paths:
  /user/login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg","","data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
swagger: "2.0"
